apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: docker-experiments-front-deployment
spec:
  template:
    metadata:
      labels:
        app: docker-experiments
        tier: front
    spec:
      containers:
        - image: topheman/docker-experiments_nginx:1.0.1
          name: nginx
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx","-s","quit"]
---
apiVersion: v1
kind: Service
metadata:
  name: docker-experiments-front-service
spec:
  selector:
    app: docker-experiments
    tier: front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer